# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 287)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.buyerTab = QtWidgets.QWidget()
        self.buyerTab.setObjectName("buyerTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.buyerTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buyerSearchLineEdit = QtWidgets.QLineEdit(self.buyerTab)
        self.buyerSearchLineEdit.setObjectName("buyerSearchLineEdit")
        self.horizontalLayout_3.addWidget(self.buyerSearchLineEdit)
        self.buyerSearchPushButton = QtWidgets.QPushButton(self.buyerTab)
        self.buyerSearchPushButton.setObjectName("buyerSearchPushButton")
        self.horizontalLayout_3.addWidget(self.buyerSearchPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.buyerTableWidget = QtWidgets.QTableWidget(self.buyerTab)
        self.buyerTableWidget.setRowCount(3)
        self.buyerTableWidget.setObjectName("buyerTableWidget")
        self.buyerTableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.buyerTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyerTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyerTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyerTableWidget.setHorizontalHeaderItem(3, item)
        self.buyerTableWidget.verticalHeader().setVisible(False)
        self.buyerTableWidget.verticalHeader().setDefaultSectionSize(35)
        self.verticalLayout_2.addWidget(self.buyerTableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buyerPageLabel = QtWidgets.QLabel(self.buyerTab)
        self.buyerPageLabel.setObjectName("buyerPageLabel")
        self.horizontalLayout_2.addWidget(self.buyerPageLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buyerDeletePushButton = QtWidgets.QPushButton(self.buyerTab)
        self.buyerDeletePushButton.setObjectName("buyerDeletePushButton")
        self.horizontalLayout.addWidget(self.buyerDeletePushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buyerLastPushButton = QtWidgets.QPushButton(self.buyerTab)
        self.buyerLastPushButton.setObjectName("buyerLastPushButton")
        self.horizontalLayout.addWidget(self.buyerLastPushButton)
        self.buyerNextPushButton = QtWidgets.QPushButton(self.buyerTab)
        self.buyerNextPushButton.setObjectName("buyerNextPushButton")
        self.horizontalLayout.addWidget(self.buyerNextPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.buyerTab, "")
        self.storeTab = QtWidgets.QWidget()
        self.storeTab.setObjectName("storeTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.storeTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.storeSearchLineEdit = QtWidgets.QLineEdit(self.storeTab)
        self.storeSearchLineEdit.setObjectName("storeSearchLineEdit")
        self.horizontalLayout_6.addWidget(self.storeSearchLineEdit)
        self.storeSearchPushButton = QtWidgets.QPushButton(self.storeTab)
        self.storeSearchPushButton.setObjectName("storeSearchPushButton")
        self.horizontalLayout_6.addWidget(self.storeSearchPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.storeTableWidget = QtWidgets.QTableWidget(self.storeTab)
        self.storeTableWidget.setRowCount(3)
        self.storeTableWidget.setObjectName("storeTableWidget")
        self.storeTableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.storeTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.storeTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.storeTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.storeTableWidget.setHorizontalHeaderItem(3, item)
        self.storeTableWidget.verticalHeader().setVisible(False)
        self.storeTableWidget.verticalHeader().setDefaultSectionSize(35)
        self.verticalLayout_3.addWidget(self.storeTableWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.storePageLabel = QtWidgets.QLabel(self.storeTab)
        self.storePageLabel.setObjectName("storePageLabel")
        self.horizontalLayout_5.addWidget(self.storePageLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.storeDeletePushButton = QtWidgets.QPushButton(self.storeTab)
        self.storeDeletePushButton.setObjectName("storeDeletePushButton")
        self.horizontalLayout_4.addWidget(self.storeDeletePushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.storeLastPushButton = QtWidgets.QPushButton(self.storeTab)
        self.storeLastPushButton.setObjectName("storeLastPushButton")
        self.horizontalLayout_4.addWidget(self.storeLastPushButton)
        self.storeNextPushButton = QtWidgets.QPushButton(self.storeTab)
        self.storeNextPushButton.setObjectName("storeNextPushButton")
        self.horizontalLayout_4.addWidget(self.storeNextPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.storeTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.buyerSearchPushButton.setText(_translate("Form", "搜索"))
        item = self.buyerTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "选择"))
        item = self.buyerTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "买家编号"))
        item = self.buyerTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "昵称"))
        item = self.buyerTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "信誉度"))
        self.buyerPageLabel.setText(_translate("Form", "“页码”"))
        self.buyerDeletePushButton.setText(_translate("Form", "删除"))
        self.buyerLastPushButton.setText(_translate("Form", "上一页"))
        self.buyerNextPushButton.setText(_translate("Form", "下一页"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buyerTab), _translate("Form", "用户"))
        self.storeSearchPushButton.setText(_translate("Form", "搜索"))
        item = self.storeTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "选择"))
        item = self.storeTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "商家编号"))
        item = self.storeTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "店铺名称"))
        item = self.storeTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "信誉度"))
        self.storePageLabel.setText(_translate("Form", "“页码”"))
        self.storeDeletePushButton.setText(_translate("Form", "删除"))
        self.storeLastPushButton.setText(_translate("Form", "上一页"))
        self.storeNextPushButton.setText(_translate("Form", "下一页"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.storeTab), _translate("Form", "商家"))

